// AUTOGENERATED. DO NOT MODIFY.
// To modify this file, update the source template,
// or run the compiler: go/carbon-service-code-gen-mwtc.
// Source template: javascript/materialdesign/tokens/compiler/formats/flutter/templates/typescale_struct.dart

class TypescaleStruct {
  const TypescaleStruct({
    required this.fontSize,
    required this.fontWeight,
    required this.lineHeight,
    required this.letterSpacing,
  });

  final double fontSize;
  final double fontWeight;
  final double lineHeight;
  final double letterSpacing;
}
